using System;

namespace Interpolant.Configuration.Interpolation.Simplicial
{
    /// <summary>
    /// Defines the plane to associate with each simplex in the simplicial
    /// mesh generated by the interpolant.
    /// </summary>
    public enum SimplicialOrder
    {
        /// <summary>
        /// 
        /// </summary>
        Linear = 1,

        /// <summary>
        /// 
        /// </summary>
        [Obsolete("Not yet implemented.")]
        Quadratic = 2,

        /// <summary>
        /// 
        /// </summary>
        [Obsolete("Not yet implemented.")]
        Cubic = 3,

        /// <summary>
        /// 
        /// </summary>
        [Obsolete("Not yet implemented.")]
        CloughTocher = 4,

        /// <summary>
        /// 
        /// </summary>
        [Obsolete("Not yet implemented.")]
        PowellSabin = 5
    }
}
